### PR TITLE
refactor

### PR DESCRIPTION
**Pull request by hiba-machfej**
I tried`listWritings_1` and it is not working. So I removed it. I also removed a few comments. 
Does the fn  `listWritings_1`and the comments has a purpose I am missing ?

### CODE REVIEW

**Comment by mhassanist** [comment]
> I tried`listWritings_1` and it is not working. So I removed it. I also removed a few comments. Does the fn `listWritings_1`and the comments has a purpose I am missing ?

What happened when you tried? 
in the video I was using it to demonstrate something. also the comments. It's fine to remove them from the Repo.

**Comment by hiba-machfej** [comment]
> listWritings_1

I got the comments actually: 
Screen Shot 2022-03-04 at 11 47 04 AM

**Comment by mhassanist** [comment]
> > listWritings_1
> 
> I got the comments actually: Screen Shot 2022-03-04 at 11 47 04 AM

Yes exactly. I explained in the video that: if you use this approach, this is what u will get.

**Comment by hiba-machfej** [comment]
> > > listWritings_1
> > 
> > 
> > I got the comments actually: Screen Shot 2022-03-04 at 11 47 04 AM
> 
> Yes exactly. I explained in the video that: if you use this approach, this is what u will get.

Ok then should we keep it,  I can add the explanation to it and how to use it and what to expect also to the docs?

**Comment by mhassanist** [comment]
No need to keep it. Whoever sees the video, will know.

**Pull request merged**
